In [1]:
import nflreadpy as nfl
import pandas as pd 
import numpy as np 
import warnings
pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore')

In [2]:
schedules = nfl.load_schedules([2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [3]:
type(schedules)

polars.dataframe.frame.DataFrame

In [4]:
schedules = schedules.to_pandas()

In [5]:
schedules.head()

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
0,2016_01_CAR_DEN,2016,REG,1,2016-09-08,Thursday,20:30,CAR,20,DEN,21,Home,1,41,0,2016090800,56901,NaN,201609080den,4094.0,400874484,NaN,7,7,-150.0,136.0,-3.0,101.0,-111.0,40.5,-110.0,-100.0,0,outdoors,grass,85.0,10.0,00-0027939,00-0032156,Cam Newton,Trevor Siemian,Ron Rivera,Gary Kubiak,Gene Steratore,DEN00,Sports Authority Field at Mile High
1,2016_01_TB_ATL,2016,REG,1,2016-09-11,Sunday,13:00,TB,31,ATL,24,Home,-7,55,0,2016091100,56902,NaN,201609110atl,4095.0,400874522,NaN,7,7,120.0,-133.0,2.5,-102.0,-108.0,46.5,-105.0,-105.0,1,dome,fieldturf,NaN,NaN,00-0031503,00-0026143,Jameis Winston,Matt Ryan,Dirk Koetter,Dan Quinn,Jeff Triplette,ATL00,Georgia Dome
2,2016_01_BUF_BAL,2016,REG,1,2016-09-11,Sunday,13:00,BUF,7,BAL,13,Home,6,20,0,2016091101,56903,NaN,201609110rav,4096.0,400874510,NaN,7,7,151.0,-167.0,3.0,105.0,-116.0,44.5,-108.0,-102.0,0,outdoors,grass,84.0,8.0,00-0028118,00-0026158,Tyrod Taylor,Joe Flacco,Rex Ryan,John Harbaugh,Brad Allen,BAL00,M&T Bank Stadium
3,2016_01_CHI_HOU,2016,REG,1,2016-09-11,Sunday,13:00,CHI,14,HOU,23,Home,9,37,0,2016091102,56904,NaN,201609110htx,4097.0,400874511,NaN,7,7,210.0,-235.0,5.5,-107.0,-103.0,43.0,100.0,-110.0,0,closed,fieldturf,NaN,NaN,00-0024226,00-0029682,Jay Cutler,Brock Osweiler,John Fox,Bill O'Brien,Peter Morelli,HOU00,NRG Stadium
4,2016_01_GB_JAX,2016,REG,1,2016-09-11,Sunday,13:00,GB,27,JAX,23,Home,-4,50,0,2016091103,56905,NaN,201609110jax,4098.0,400874486,NaN,7,7,-179.0,161.0,-3.5,-100.0,-110.0,47.0,-110.0,-100.0,0,outdoors,grass,90.0,3.0,00-0023459,00-0031407,Aaron Rodgers,Blake Bortles,Mike McCarthy,Gus Bradley,Carl Cheffers,JAX00,EverBank Field

In [6]:
schedules.columns

Index(['game_id', 'season', 'game_type', 'week', 'gameday', 'weekday',
       'gametime', 'away_team', 'away_score', 'home_team', 'home_score',
       'location', 'result', 'total', 'overtime', 'old_game_id', 'gsis',
       'nfl_detail_id', 'pfr', 'pff', 'espn', 'ftn', 'away_rest', 'home_rest',
       'away_moneyline', 'home_moneyline', 'spread_line', 'away_spread_odds',
       'home_spread_odds', 'total_line', 'under_odds', 'over_odds', 'div_game',
       'roof', 'surface', 'temp', 'wind', 'away_qb_id', 'home_qb_id',
       'away_qb_name', 'home_qb_name', 'away_coach', 'home_coach', 'referee',
       'stadium_id', 'stadium'],
      dtype='str')

In [8]:
combine = nfl.load_combine([2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025])
combine = combine.to_pandas()
combine.info()

<class 'pandas.DataFrame'>
RangeIndex: 3425 entries, 0 to 3424
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   season       3425 non-null   int32
 1   draft_year   2128 non-null   float64
 2   draft_team   2128 non-null   str
 3   draft_round  2128 non-null   float64
 4   draft_ovr    2128 non-null   float64
 5   pfr_id       3026 non-null   str
 6   cfb_id       3180 non-null   str
 7   player_name  3425 non-null   str
 8   pos          3425 non-null   str
 9   school       3425 non-null   str
 10  ht           3396 non-null   str
 11  wt           3401 non-null   float64
 12  forty        2674 non-null   float64
 13  bench        1859 non-null   float64
 14  vertical     2607 non-null   float64
 15  broad_jump   2539 non-null   float64
 16  cone         1624 non-null   float64
 17  shuttle      1726 non-null   float64
dtypes: float64(10), int32(1), str(7)
memory usage: 694.4 KB

In [9]:
combine.head()

,season,draft_year,draft_team,draft_round,draft_ovr,pfr_id,cfb_id,player_name,pos,school,ht,wt,forty,bench,vertical,broad_jump,cone,shuttle
0,2016,NaN,NaN,NaN,NaN,AbdeMe00,mehdi-abdesmad-1,Mehdi Abdesmad,DE,Boston Col.,6-6,284.0,5.10,25.0,29.5,108.0,7.55,4.62
1,2016,NaN,NaN,NaN,NaN,NaN,vernon-adams-1,Vernon Adams,QB,Oregon,5-11,200.0,4.83,NaN,29.5,114.0,6.82,4.20
2,2016,2016.0,New York Giants,6.0,184.0,AdamJe01,jerell-adams-1,Jerell Adams,TE,South Carolina,6-5,247.0,4.64,NaN,32.5,117.0,7.05,4.31
3,2016,NaN,NaN,NaN,NaN,AddiBr01,bralon-addison-1,Bralon Addison,WR,Oregon,5-9,197.0,4.66,13.0,34.5,116.0,6.95,4.14
4,2016,2016.0,Tampa Bay Buccaneers,2.0,59.0,AguaRo00,roberto-aguayo-1,Roberto Aguayo,K,Florida State,6-0,207.0,4.96,NaN,NaN,NaN,NaN,NaN

In [10]:
combine[(combine['school']=='LSU') & (combine['draft_year']==2021)]

,season,draft_year,draft_team,draft_round,draft_ovr,pfr_id,cfb_id,player_name,pos,school,ht,wt,forty,bench,vertical,broad_jump,cone,shuttle
1733,2021,2021.0,Cincinnati Bengals,1.0,5.0,ChasJa00,jamarr-chase-1,Ja'Marr Chase,WR,LSU,6-0,201.0,4.34,NaN,41.0,132.0,6.96,3.99
1747,2021,2021.0,Dallas Cowboys,4.0,115.0,CoxxJa00,jabril-cox-1,Jabril Cox,LB,LSU,6-3,232.0,NaN,NaN,NaN,NaN,NaN,NaN
1889,2021,2021.0,Denver Broncos,7.0,237.0,VincKa00,kary-vincent-jr-1,Kary Vincent Jr.,CB,LSU,5-9,185.0,4.36,8.0,35.5,117.0,NaN,NaN
1929,2021,2021.0,Tennessee Titans,6.0,205.0,McMaRa00,racey-mcmath-1,Racey McMath,WR,LSU,6-2,217.0,4.36,NaN,34.0,124.0,7.38,4.38
2027,2021,2021.0,Cincinnati Bengals,4.0,122.0,ShelTy00,tyler-shelvin-1,Tyler Shelvin,DT,LSU,6-2,350.0,5.40,NaN,28.5,97.0,8.15,5.05
2047,2021,2021.0,Philadelphia Eagles,6.0,224.0,StevJa00,jacoby-stevens-1,Jacoby Stevens,S,LSU,6-1,212.0,4.63,NaN,42.0,130.0,NaN,NaN

In [21]:
ffverse = nfl.load_ffverse
type(ffverse)

module

In [16]:
dir(ffverse)

['DataFormat',
 'Literal',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'get_current_season',
 'get_downloader',
 'load_ff_opportunity',
 'load_ff_playerids',
 'load_ff_rankings',
 'pl']

In [20]:
ffverse.get_downloader()

In [25]:
lst = list(dir(nfl))
print(lst)

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'cache', 'clear_cache', 'config', 'downloader', 'get_current_season', 'get_current_week', 'load_combine', 'load_contracts', 'load_depth_charts', 'load_draft_picks', 'load_ff_opportunity', 'load_ff_playerids', 'load_ff_rankings', 'load_ffverse', 'load_ftn_charting', 'load_injuries', 'load_nextgen_stats', 'load_officials', 'load_participation', 'load_pbp', 'load_pfr_advstats', 'load_player_stats', 'load_players', 'load_rosters', 'load_rosters_weekly', 'load_schedules', 'load_snap_counts', 'load_stats', 'load_team_stats', 'load_teams', 'load_trades', 'utils_date', 'version']

In [31]:
contracts = nfl.load_contracts().to_pandas()

In [45]:
contracts.head(1)

,player,position,team,is_active,year_signed,years,value,apy,guaranteed,apy_cap_pct,inflated_value,inflated_apy,inflated_guaranteed,player_page,otc_id,gsis_id,height,weight,college,draft_year,draft_round,draft_overall,draft_team,date_of_birth,season_history,contract_history
0,Joe Burrow,QB,Bengals,True,2023,5.0,275.0,55.0,146.51,0.245,368.460854,73.692171,196.302544,https://overthecap.com/player/joe-burrow/8741/,8741,00-0036442,"6'4""",215,LSU,2020.0,1.0,1.0,Bengals,NaN,"[{'year': '2020', 'team': 'Bengals', 'base_sal...","[{'team': 'Bengals', 'contract_type': 'Drafted..."

In [36]:
depth_chart = nfl.load_depth_charts(2026).to_pandas()

In [40]:
depth_chart.columns

Index(['dt', 'team', 'player_name', 'espn_id', 'gsis_id', 'pos_grp_id',
       'pos_grp', 'pos_id', 'pos_name', 'pos_abb', 'pos_slot', 'pos_rank'],
      dtype='str')

In [41]:
depth_chart.head(1)

,dt,team,player_name,espn_id,gsis_id,pos_grp_id,pos_grp,pos_id,pos_name,pos_abb,pos_slot,pos_rank
0,2026-08-19T07:43:54Z,ARI,Josh Sweat,3693166,00-0034381,16,Base 4-3 D,11,Left Defensive End,LDE,1,1

In [42]:
dp = nfl.load_draft_picks([2026]).to_pandas()

In [43]:
dp.info()

<class 'pandas.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 36 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   season            257 non-null    int32
 1   round             257 non-null    int32
 2   pick              257 non-null    int32
 3   team              257 non-null    str
 4   gsis_id           230 non-null    str
 5   pfr_player_id     257 non-null    str
 6   cfb_player_id     205 non-null    str
 7   pfr_player_name   257 non-null    str
 8   hof               257 non-null    bool
 9   position          257 non-null    str
 10  category          257 non-null    str
 11  side              256 non-null    str
 12  college           257 non-null    str
 13  age               215 non-null    float64
 14  to                0 non-null      float64
 15  allpro            257 non-null    int32
 16  probowls          257 non-null    int32
 17  seasons_started   257 non-null    int32
 18  w_av              0 non-null      float64
 19  car_av            0 non-null      object
 20  dr_av             0 non-null      float64
 21  games             0 non-null      float64
 22  pass_completions  0 non-null      float64
 23  pass_attempts     0 non-null      float64
 24  pass_yards        0 non-null      float64
 25  pass_tds          0 non-null      float64
 26  pass_ints         0 non-null      float64
 27  rush_atts         0 non-null      float64
 28  rush_yards        0 non-null      float64
 29  rush_tds          0 non-null      float64
 30  receptions        0 non-null      float64
 31  rec_yards         0 non-null      float64
 32  rec_tds           0 non-null      float64
 33  def_solo_tackles  0 non-null      float64
 34  def_ints          0 non-null      float64
 35  def_sacks         0 non-null      float64
dtypes: bool(1), float64(19), int32(6), object(1), str(9)
memory usage: 80.1+ KB

In [44]:
dp.head(1)

,season,round,pick,team,gsis_id,pfr_player_id,cfb_player_id,pfr_player_name,hof,position,category,side,college,age,to,allpro,probowls,seasons_started,w_av,car_av,dr_av,games,pass_completions,pass_attempts,pass_yards,pass_tds,pass_ints,rush_atts,rush_yards,rush_tds,receptions,rec_yards,rec_tds,def_solo_tackles,def_ints,def_sacks
0,2026,1,1,LVR,MEN516487,MendFe00,fernando-mendoza-1,Fernando Mendoza,False,QB,QB,O,Indiana,22.0,NaN,0,0,0,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
lfc = nfl.load_ftn_charting([2025]).to_pandas()
lfc.columns

Index(['ftn_game_id', 'nflverse_game_id', 'season', 'week', 'ftn_play_id',
       'nflverse_play_id', 'starting_hash', 'qb_location',
       'n_offense_backfield', 'n_defense_box', 'is_no_huddle', 'is_motion',
       'is_play_action', 'is_screen_pass', 'is_rpo', 'is_trick_play',
       'is_qb_out_of_pocket', 'is_interception_worthy', 'is_throw_away',
       'read_thrown', 'is_catchable_ball', 'is_contested_ball',
       'is_created_reception', 'is_drop', 'is_qb_sneak', 'n_blitzers',
       'n_pass_rushers', 'is_qb_fault_sack', 'date_pulled'],
      dtype='str')

In [48]:
lfc.head(2)

,ftn_game_id,nflverse_game_id,season,week,ftn_play_id,nflverse_play_id,starting_hash,qb_location,n_offense_backfield,n_defense_box,is_no_huddle,is_motion,is_play_action,is_screen_pass,is_rpo,is_trick_play,is_qb_out_of_pocket,is_interception_worthy,is_throw_away,read_thrown,is_catchable_ball,is_contested_ball,is_created_reception,is_drop,is_qb_sneak,n_blitzers,n_pass_rushers,is_qb_fault_sack,date_pulled
0,6734,2025_01_DAL_PHI,2025,1,1106026,40,0,0,0.0,0,False,False,False,False,False,False,False,False,False,0,False,False,False,False,False,0,0,False,2025-12-11 12:41:10.599765+00:00
1,6734,2025_01_DAL_PHI,2025,1,1106027,71,R,U,2.0,6,False,True,False,False,False,False,False,False,False,0,False,False,False,False,False,0,0,False,2025-12-11 12:41:10.599765+00:00

In [ ]:
'load_injuries', 'load_nextgen_stats', 'load_officials', 'load_participation', 'load_pbp', 'load_pfr_advstats', 'load_player_stats', 'load_players', 
'load_rosters', 'load_rosters_weekly', 'load_schedules', 'load_snap_counts', 'load_stats', 'load_team_stats', 'load_teams', 'load_trades', 'utils_date',
'version'

In [51]:
injuries = nfl.load_injuries(2025).to_pandas()

In [52]:
injuries.head(2)

,season,season_type,game_type,team,week,gsis_id,position,full_name,first_name,last_name,report_primary_injury,report_secondary_injury,report_status,practice_primary_injury,practice_secondary_injury,practice_status
0,2025,REG,REG,ARI,1,00-0026190,DE,Calais Campbell,Calais,Campbell,NaN,NaN,NaN,Not injury related - resting player,NaN,Did Not Participate In Practice
1,2025,REG,REG,ARI,1,00-0034346,G,Will Hernandez,William,Hernandez,Knee,NaN,Out,Knee,NaN,Limited Participation in Practice

In [53]:
nxtgen = nfl.load_nextgen_stats(2025).to_pandas()

In [54]:
nxtgen.columns

Index(['season', 'season_type', 'week', 'player_display_name',
       'player_position', 'team_abbr', 'avg_time_to_throw',
       'avg_completed_air_yards', 'avg_intended_air_yards',
       'avg_air_yards_differential', 'aggressiveness',
       'max_completed_air_distance', 'avg_air_yards_to_sticks', 'attempts',
       'pass_yards', 'pass_touchdowns', 'interceptions', 'passer_rating',
       'completions', 'completion_percentage',
       'expected_completion_percentage',
       'completion_percentage_above_expectation', 'avg_air_distance',
       'max_air_distance', 'player_gsis_id', 'player_first_name',
       'player_last_name', 'player_jersey_number', 'player_short_name'],
      dtype='str')

In [55]:
nxtgen.head(2)

,season,season_type,week,player_display_name,player_position,team_abbr,avg_time_to_throw,avg_completed_air_yards,avg_intended_air_yards,avg_air_yards_differential,aggressiveness,max_completed_air_distance,avg_air_yards_to_sticks,attempts,pass_yards,pass_touchdowns,interceptions,passer_rating,completions,completion_percentage,expected_completion_percentage,completion_percentage_above_expectation,avg_air_distance,max_air_distance,player_gsis_id,player_first_name,player_last_name,player_jersey_number,player_short_name
0,2025,REG,0,Caleb Williams,QB,CHI,3.195860,6.197576,8.430951,-2.233375,10.563380,62.114966,-0.504411,568,3942,27,7,90.126174,330,58.098592,64.973275,-6.874683,21.323002,66.081562,00-0039918,Caleb,Williams,18,C.Williams
1,2025,REG,0,Matthew Stafford,QB,LAR,2.799253,7.253660,9.099604,-1.845944,18.592965,58.415054,1.016988,597,4707,46,8,109.195282,388,64.991625,63.515477,1.476147,22.215867,62.297263,00-0026498,John,Stafford,9,M.Stafford

In [56]:
off = nfl.load_officials(2025).to_pandas()
off.head(2)

,game_id,game_key,official_name,position,jersey_number,official_id,season,season_type,week
0,2025090400,59843,Dyrol Prioleau,Field Judge,109,472,2025,REG,1
1,2025090400,59843,Boris Cheek,Side Judge,41,211,2025,REG,1

In [ ]:
participation = nfl.load